export const CONSTANTS = {
   
    MYSQL_DATE_FORMAT:'YYYY-MM-DD',
    MYSQL_DATE_IN_FORMAT:'DD-MM-YYYY',
    MYSQL_DATE_TIME_FORMAT:'YYYY-MM-DD HH:mm:ss',
    MYSQL_TIME_FORMAT:'YYYY-MM-DD HH:mm:ss',
    STATUS_CODE:'statusCode',
    SITE_DATE_FORMAT:'DD/MM/YYYY',
    CONTACT_US_TEMPLATE_ID:20,
    FORGOT_PASSWORD_TEMPLATE_ID:1,
    EMAIL_VERIFICATION_LINK_TEMPLATE_ID:2,
    NEW_SUBADMIN_ADDED_TEMPLATE_ID:3, 
    PASSWORD_CHANGED_TEMPLATE_ID:4,
    NEW_CUSTOMER_ADDED_TEMPLATE_ID:5, 
    PASSWORD_CHANGE_TRIGGER_EMAIL_TO_ADMIN:6,
    PAYPAL_PAY_LATER_TEMPLATE_ID: 7,
    PAYMENT_SUCCESS_FOR_PLAN_TEMPLATE_ID: 8,
    RAISE_REFUND_TEMPLATE_ID:9,
    REFUND_ACCEPTED_TEMPLATE_ID_CUSTOMER:10,
    REFUND_REJECTED_TEMPLATE_ID_CUSTOMER:11,
    REFUND_ACCEPTED_TEMPLATE_ID_AGENT:12,
    REFUND_REJECTED_TEMPLATE_ID_AGENT:13,
    RAISE_REFUND_TEMPLATE_ID_FROM_CRON:14,
    PARTIAL_REFUND_ACCEPTED_TEMPLATE_ID_CUSTOMER:15,
    INVOICE_TEMPLATE_ID:16,
    INVOICE_EMAIL_TEMPLATE_ID:17,

    NOTIFICATION_INVITE_COLLEAGUE:18,
    SEND_OTP_TEMPLATE_ID:19,
    OTP_EXPIRE_TIME:'10',
    OTP_EXPIRE_VALID_TIME:10, 
    LOGIN_SUCCESS:'Login request successfully.',
    ADMIN_FORGOT_PASSWORD_SUCCESS:'Please check the registered mail id we have sent a mail for change the password',
    FORGOT_PASSWORD_SUCCESS:'Password reset code has been sent to your registered email address successfully.',
    FORGOT_PASSWORD_SUCCESS_PHONE:'Password reset code has been sent to your phone successfully.',
    VERIFICATION_OTPSENT_SUCCESS_PHONE:'Verificaton code has been sent to your phone successfully.',
    VERIFICATION_OTPSENT_SUCCESS_EMAIL:'Verificaton code has been sent to your email successfully.',
    LOGIN_OTPSENT_SUCCESS_PHONE:'Login code has been sent to your registered phone number successfully.',
    RESEND_OTP_SUCCESS:'OTP resent successfully.',
    EMAIL_SUCCESS_VERIFY:'Email address verified successfully.',
    PHONE_SUCCESS_VERIFY:'Phone number verified successfully.',
    PASSWORD_RESET_SUCCESS:'Password changed successfully.',
    USER_PASSWORD_RESET:'Password has changed please login again with new password.',
    LOGOUT_SUCCESS:'Logout successful',
    USER_STATUS_UPDATE:'User actived successfully',
    ACCOUNT_DELETE_SUCCESS:'Account deleted successfully',
    EMAIL_CHANGE_SUCCESS:'Email address changed successfully please verify your new email address',
    INFORMATION_UPDATED:'Information updated successfully',
    PASSWORD_SUCCESS_VERIFY:'Password changed successfully',
    EMAIL_VERIFICATION_PENDING:'Your account verification is pending.',
    ACCOUNT_DELETED:'Account has been deleted',
    PASSWORD_DIFF:'New password must be different from old',
    USER_NOT_EXIST:'User does not exists.',
    INCORRECT_EMAIL_PASSWORD:'Invalid user credentials',
    INCORRECT_PASSWORD:'Password is incorrect',
    EMAIL_TAKEN:'Sorry! email address is already being used.',
    PHONE_TAKEN:'Sorry! phone number is already being used.',
    EMAIL_IS_SAME:'New Email address is same as old.',
    EMAIL_IS_ICORRECT:'Email address is not correct.',
    RECORD_FOUND:'Record Found',
    RECORD_NOT_FOUND: 'No Record Found!',
    HISTORY_NOT_FOUND:'History not found.',
    LOCATION_NOT_FOUND:'No locations found.',
    ROUTE_NOT_FOUND:'No routes found.',
    EMAIL_ID_NOT_EXIST:'Email id does not exists.',
    PROFILE_UPDATED_SUCCESSFULLY: "Profile updated successfully.",
    INVALID_EMAIL_PASSWORD: 'Inavild email id and password.',
    PHONE_ALREADY_EXIST:'Phone number already exists.',
    EMAIL_ALREADY_EXIST:'Email address already exists.',
    EMAIL_SENT_TO: 'Email sent to successfully.',
    PASSWORD_UPDATED_SUCCESSFULLY: "Password updated successfully.",
    OLD_PASSWORD_DOESNT_MATCH: "Old password doesn\'t match. Please try again.",
    SUCCESS: "Success",
    FAILED: "Failed",
    INVALID_OTP:"Invalid OTP",
    UNAUTHORIZED_ACCESS: 'Unauthorized Access.',
    USER_NOT_FOUND: "User not found.",
    FRIEND_NOT_FOUND: "No nearby friends found.",
    NO_FRND_FOUND:"No friends found",
    USER_NOT_FOUND_WITH_REGISTERED_PHONE: "No registered user found with this phone number, Try using different phone number.",
    AUTHENTICATION_FAILED: "Invalid credentials",
    NOT_AN_ADMIN: 'You are not an admin. Only admin can perform this action.',
    REQUIRED_FIELDS_ARE_MISSING: 'Required fields are missing.',
    ACCOUNT_NOT_VERIFIED:'Account not verified.',
    SOMETHING_WENT_WRONG: 'Something went wrong! Please try again.',
    EVENT_ALREADY_EXISTS: 'This event already exist for this client and event provider.',
    USER_NOT_ACTIVE: "User account is not active.",
    INVALID_TOKEN: "Token is not valid.",
    ADDED_SUCCESSFULLY: "Added successfully.", 
    UPDATED_SUCCESSFULLY: "Updated successfully.", 
    ALREADY_EXISTS: "Already Exists! please try again.",
    ACTIVATED_SUCCESSFULLY: "Activated successfully.",
    DEACTIVATED_SUCCESSFULLY: "Deactivated successfully.",
    DELETED_SUCCESSFULLY: "Deleted Successfully.",
    EMAIL_ALREADY_EXISTS: "Email already exists.",
    USERNAME_ALREADY_EXISTS: "Username already exists.",
    PRODUCT_ALREADY_EXISTS: "Product already exists in this category.",
    YOUR_ACCOUNT_NOT_ACTIVE:  "Your account is not active. Please contact admin for more information.",
    PAYMENT_LINK_SUCCESSFULLY_SENT_TO_CUSTOMER: "Payment link successfully sent to customer's email.",
    TOKEN_EXPIRED: "Sorry! this URL has expired.",
    OTP_EXPIRE:"Sorry! this OTP has expired.",
    TOKEN_EXPIRED_FOR_RESET_PWD: "This token has been expired or you have used once.",
    CAN_NOT_UPDATE: "Sorry, you cannot make further changes as request status has changed.",
    ALREADY_REQUEST_REFUND: "You have already requested refund for this subscription.",
    NOT_CHAIRMAN: "Only chairman has this permission.",
    NOT_CEO_GM: "Permission can only be given to CEO or General Manager.",
    PERMISSON_CREATED: "Permission created successfully.",
    PERMISSON_UPDATED: "Permission updated successfully.",
    PERMISSION_DENIED: "Sorry! You do not have permissions to access this section. Please contact Admin for more details.",
    ALREADY_REQUESTED: "You have already requested for this action.",
    NO_COST_DEDUCTED_AS_COST_NOT_FOUND_IN_YOUR_COUNTRY: "No cost deducted for this video as price is not enterd in your country.",
    VIDEO_STREAM_NOT_AVALIABLE: "You requested video stream not avaliable",
    CARD_SAVED_SUCCESSFULLY: "Card saved successfully.",
    PAYMENT_SUCCESSFUL: "Payment Successful.",
    COUNTRY_DOES_NOT_MATCH: "Your country does not match with current country.",
    PRODUCT_NOT_FOR_YOUR_COUNTRY: "This product is not available  for your country.",
    PRODUCT_NOT_EXISTS: "This product does not exists.",
    SAVED_SUCCESSFULLY: "Saved Successfully.",
    TC_NOT_ACCEPTED: "Please accept terms and conditions to continue browsing the site.",
    TC_NOT_ACCEPTED_BEFORE_PURCHASE: "Sorry! Customer must have to accept our terms and conditions before purchasing any subscription.",
    LAST_CARD_WARNING: "Sorry! Primary Card cannot be removed as the auto-renewal is active.",
    TAX_ALREADY_EXISTS: "Sorry! Tax is already active for this country.",
    TAX_ALREADY_EXISTS_FOR_COUNTRIES: "Sorry! Tax already exists for some countries.",
    NO_SUFFICIENT_BALANCE_FOR_THIS_VIDEO: "You don’t have a sufficient subscription balance to use this product. Please select another product or renew your subscription.",
    INVALID_FILE_TYPE:"Invalid file type!",
    CONTACT_US_SUCCESS_MSG:"Thank you for contacting us. We will respond to you as soon as possible.",
    SESSION_EXPIRED:"Session expired!",
    REQUEST_ACCEPTED:"Request accepted",
    REQUEST_REJECTED:"Request rejected",
    APP_TITLE:"London Application",
    FRIEND_REQUEST_ACCEPTED:"has accepted your friend request.",
    FRIEND_REQUEST_SENT:"sent you a friend request.",
    LOCATION_ALREADY_EXIST:"Location already exists.",
    JOURNEY_ALREADY_EXIST:"Journey already exists."
};

export const Codes = {
    OK: 200,
    CREATED: 201,
    ACCEPTED: 202,
    NO_CONTENT: 204,
    MOVED_PERMANENTLY: 301,
    FOUND: 301,
    NOT_MODIFIED: 304,
    BAD_REQUEST: 400,
    UNAUTHORIZED: 401,
    FORBIDDEN: 403,
    NOT_FOUND: 404,
    METHOD_NOT_ALLOWED: 405,
    NOT_ACCEPTABLE: 406,
    INTERNAL_SERVER_ERROR: 500,
    NOT_IMPLEMENTED: 501,
    ALREADY_EXIST: 409,
    NOT_VERIFIED:505,
    SESSION_EXPIRE:440
};